local set = vim.opt

set.cursorline = true
set.number = true
set.autoindent = true
set.relativenumber = false
set.signcolumn = "yes"
set.expandtab = true
set.shiftwidth = 2
set.tabstop = 2
set.scrolloff = 15
set.splitbelow = true
set.updatetime = 250
set.splitright = true
set.termguicolors = true
set.smartindent = true
set.wrap = false
set.smartcase = true
set.showmode = false
set.conceallevel = 0
set.cmdheight = 1
set.clipboard = "unnamedplus"
set.backup = false
set.pumheight = 10
set.fileencoding = "utf-8"
set.numberwidth = 4
set.completeopt = { "menu", "menuone", "noselect" }
